Feat: 마이페이지 회원정보 완성, 세부 페이지 추가
myalley-project/myalley-fe pull request #162
Opened 2023-01-27 16:41 UTC by gandy818

- 회원정보 수정 ui 작업, api 연결 완료입니다.
- 내가 쓴 한줄 리뷰, 내가 쓴 블로그 리뷰, 내가 쓴 메이트모집글을 쿼리스트링으로 변경했습니다. 페이지네이션에 따라 url로 접근이 가능합니다.
- 북마크한 전시회, 북마크한 블로그 리뷰, 북마크한 메이트모집글 역시 위와 동일합니다. 
- 마이페이지에 하위 페이지들이 많아 구분이 편하도록 파일명을 수정했습니다.

- 회원정보 페이지의 input state 에 따른 디자인은 디자이너님 답변 듣고 추가할 예정입니다.

2023-01-28 05:40 UTC, YesunPark requested changes
코멘트 확인부탁드릴게요!

2023-01-28 05:40 UTC, YesunPark commented on src/utils/isApiError.tsx
> +    if (errorCode === 403 && errorMsg === "Acess토큰 만료")
나영님 혹시 이건 어디서 변경된건가요?[ api 문서](https://www.notion.so/API-73d431b2d38e4618b9f10a0d0e142af1?p=5ac6343b11c14650b69c6931014ae46e&pm=s) 보시면 ACCESS토큰 만료라고 오는게 맞는데 변경됐다고 전달받으셨나요?

2023-01-28 15:05 UTC, gandy818 commented on src/utils/isApiError.tsx
> +    if (errorCode === 403 && errorMsg === "Acess토큰 만료")
변경됐다고 전달받은건 아니고 제가 테스트했던 api 에선 전부 Acess토큰 이라고 보내주시더라구요!
확인 한번 부탁드릴게요! 일단 제가 발견한건 로그아웃 api , 회원정보 조회 api, 회원정보 수정 api입니다.

2023-01-28 15:21 UTC, gandy818 commented on src/utils/isApiError.tsx
> +    if (errorCode === 403 && errorMsg === "Acess토큰 만료")
영진님과 얘기한 결과 대문자로 통일하기로 해서 다시 원래대로 수정했습니다 확인 부탁드려요!

2023-01-29 08:33 UTC, YesunPark approved these changes

2023-01-29 14:02 UTC, merged