Feat: 한줄 리뷰 CRUD 기능 작성
myalley-project/myalley-fe pull request #165
Opened 2023-01-29 07:50 UTC by caffesale

1. ReviewWrapper 컴포넌트는 필터 선택 상태에 따라 한줄 리뷰와 블로그 리뷰를 보여주기 위한 컴포넌트입니다.
2. 작성과 수정에 둘 다 사용해야 하기 때문에 OnelineWrapper 컴포넌트를 일부 변경하였습니다.
    - 빈 항목을 체크하는 유효성 검사 부분에 문제가 있어 잠시 주석 처리해두겠습니다.
3. OnelineCard 컴포넌트에 수정, 삭제 버튼을 구현했습니다.
4. 한줄 리뷰 api와 관련된 temp 폴더 삭제했습니다.

2023-01-29 08:49 UTC, YesunPark requested changes
수고하셨습니다 코멘트 확인 부탁드려요!

추가로 onelineReviewapis.tsx는 oneLineReviewApis.tsx로 바꿔주시고,
types폴더에 있는 거는 d.ts로 형식통일 부탁드릴게요

2023-01-29 08:49 UTC, YesunPark commented on src/components/onelineReview/OnelineCard.tsx
> +          ) : null}
혹시 &&을 사용하지 않고 전부
'조건' ? '참이면 나올 값' : null
을 사용하신 이유를 알 수 있을까요?

2023-01-29 08:49 UTC, YesunPark commented on src/pages/OnelineWrapper.tsx
> +  const timeHandler = (e: React.MouseEvent) => {
저희 코드 컨벤션이 동사가 앞에 오는거라 이런 함수는 handleTime 이런 식으로 작성해주셔야 하는데...! 시간될 때 수정부탁드립니다ㅠ

2023-01-29 08:49 UTC, YesunPark commented on src/pages/OnelineWrapper.tsx
> +  const timeHandler = (e: React.MouseEvent) => {
이건 시간이 안되시면 리팩토링 기간에라도 진행 부탁드립니다!

2023-01-31 16:11 UTC, YesunPark commented
동규님 컴포넌트 명은 변경하신 것 같은데 파일명은 그대로라 변경 부탁드려요!!

2023-02-01 04:32 UTC, caffesale commented
> 동규님 컴포넌트 명은 변경하신 것 같은데 파일명은 그대로라 변경 부탁드려요!!

oneLine타입 파일과 컴포넌트명 다시 수정했습니다.

2023-02-01 11:59 UTC, YesunPark approved these changes

2023-02-01 12:00 UTC, merged