Feat: BlogReviewListWrapper 컴포넌트 작성
myalley-project/myalley-fe pull request #182
Opened 2023-01-30 10:16 UTC by caffesale

- 블로그 리뷰 카드를 담아두는 단순 래퍼입니다.
- 상위 컴포넌트에서 bloginfo 배열을 props로 내려 받습니다.
- BlogReviewResponse interface를 받아 카드를 map함수로 순환시킵니다.
- 블로그 리뷰의 read에 해당합니다.

2023-01-30 14:13 UTC, YesunPark requested changes
동규님 확인했습니다 몇가지 수정부탁드려요!
1. pages의 BlogReviewPage컴포넌트에서 Page는 빼주세요!
파일명이랑 컴포넌트명 다 BlogReview로만 하면 충분할 것 같습니다:)
2. apis의 onelineReviewapis 파일명 컨벤션 지켜서 수정해주세요~!
3. apimultipartInstance는 무엇일까요?? 헤더의 컨텐츠 타입만 바뀌고 나머지는 똑같은 것 같은데, 그러면 기존 apiInstance에서 설정을 따로 해주셔도 될 것 같아요

2023-01-30 18:26 UTC, gandy818 reviewed
확인했습니다 코멘트 확인 부탁드려요 ~!

2023-01-30 18:26 UTC, gandy818 commented on src/apis/onelineReviewapis.tsx
> +      `/blogs/exhibitions/${exhibitionId}?page=${pageNo}&order=${orderType}`
동규님 여기 api endpoint가 blogs 가 맞나 다시 한번 확인 부탁드려요.
파일명은 onlineReivewApi로 되어있어서요!

2023-01-30 18:26 UTC, gandy818 commented on src/components/blogreview/BlogReviewList.tsx
> +`;
주석 지워주면 더 깔끔할 것 같아요!

2023-01-31 12:41 UTC, YesunPark requested changes
BlogReviewPage 컴포넌트에서 Page는 빼주세요!

2023-02-01 10:22 UTC, caffesale commented
1. 수정하겠습니다.
2. 해당 부분은 로컬에서 다른 브랜치로 작업중인데 한줄 리뷰 pr이 병합되고 나면 머지해서 반영할 예정입니다
3. 확인했습니다

2023-02-01 12:01 UTC, YesunPark approved these changes

2023-02-01 12:01 UTC, YesunPark commented
승인했습니다 컨플릭트 해결하고 테스트후 머지부탁드려요!

2023-02-04 09:43 UTC, closed without merging