Feat: useSilentRefresh 작성
myalley-project/myalley-fe pull request #252
Opened 2023-02-05 11:33 UTC by caffesale

- 30분 간격으로 refreshToken을 확인하고 토큰이 있다면 요청을 보내 accessToken과 refreshToken을 새로 받아오는 훅입니다.
- APP.tsx 컴포넌트에서 자동실행되기 때문에 다른 컴포넌트에서 추가적으로 호출하거나 코드를 작성하실 필요는 없습니다. 
- 에러가 발생하여 토큰 갱신에 실패하는 경우 훅의 작동은 자동으로 중지됩니다.

2023-02-05 12:55 UTC, YesunPark requested changes
궁금한 점이 있습니다!

1. 일정 간격으로 액세스 토큰을 리프레시하는 점은 좋으나 2시간이 최대인데 30분마다 요청을 해야할 필요가 있을지가 궁금합니다. 1시간으로 하는 건 어떨까요? 단순 의견이니 동규님 의견도 부탁드려요!

2. 만약 이 훅을 적용하신다면 토큰이 필요한 api 요청을 했을 때 응답으로 'ACCESS토큰 만료'응답이 올 때의 경우는 따로 대비 안하실 예정인가요?

3. 사이트가 렌더링 될 때 처음 한번 무조건 실행되고, 그다음 30분마다 다시 실행되나요? 만약 처음 한번 무조건 살행이 되지 않는다면 제 생각엔 이 로직만으로는 액세스 토큰 만료응답에 대비하지 못할 것 같아요... ex) 사용자가 한번 로그인 후 로그아웃 하지 않은 채로 사이트를 나가고, 일정 시간(액세스 토큰만료시간보다 긴 시간) 후 재접속을 했을때는 그 전 액세스토큰이 있는 상태고,  만약 그 상태에서 토큰필요한 요청을 하면 액세스 토큰 만료 응답을 받음

4. 서버에 리프레시토큰인증 요청을하고, accessToken이랑 refreshToken이 있으면 로컬스토리지에 set하고 그 이후 동작은 없는데, 리프레시 토큰도 만료되었다는 에러메세지를 받으면 '자동 로그인 기간이 만료되었습니다. 다시 로그인해주세요.' 이런식으로 알림을 띄우고 로그아웃 한 다음 로그인 페이지로 이동하는 로직이 있어야 할 것 같아요. 해당 에러메세지는 api 문서 '리프레시토큰인증' 부분 확인해주세요!

2023-02-06 14:45 UTC, caffesale commented
> 
1. 30분은 임의로 설정한 값이기 때문에 변경해도 얼마든지 문제 없습니다. 이상적인 상황은 엑세스 토큰을 받아올 때 이미 expire시점을 함께 저장하고 그것에 맞춰 만료되기 직전에 받아오는 방식이지만, 그렇게 하면 엑세스 토큰의 형태를 변형해야 하기 때문에 이미 사용하고 있는 많은 컴포넌트에 영향을 주기 때문에 방식을 바꿨습니다.

2. react query로 보다 일반적인 에러형에만 대응하고 있기 때문에 토큰 관련 에러에는 따로 대응하지 않을 것 같습니다.

3. 말씀하신대로 완전히 대응하지는 못합니다. 제 생각에 jwt토큰을 사용할 때 이상적인 상황은 리프레쉬 토큰을 세션에 보관하거나 1번과 같이 만료기간을 access토큰과 함께 저장하는 방식인데, 이미 그렇게 수정하기에는 소요가 많아 미봉책을 사용했습니다.

4. 해당 훅은 이름대로 백그라운드에서 조용히 실행되며, 사용자가 모르게 동작합니다. 지적하신대로 훅의 동작 인터벌과 사용자 행동의 괴리가 있기 때문에, 오히려 경고창을 띄우면 사용자 경험을 저해할까 우려했습니다. 필요하시다면 동작 로직을 수정하겠습니다.

2023-02-07 11:37 UTC, YesunPark commented
2. 이 부분이 제가 우려하는 상황입니다. 동규님께서 엑세스토큰만료 관련 로직을 따로 작성을 안하신다면 위에서 제가 언급한 3번같은 경우에 사용자는 왜 안되는지 모르고 계속 똑같은 시도를 반복할 것 같습니다. -> 관련 로직이 없으면 계속 시도해도 계속 에러가 나겠죠 30분이 지나기 전까진
   -1) 사이트가 렌더링될 때 무조건 한번 실행 후 이후 30분마다 실행되게 하던지
   -2) 엑세스 토큰만료 관련 로직을 따로 작성하시던지 
   해야 할 것 같습니다

4. 다른 사이트를 이용하다가 로그인기간이 만료되면 다시 로그아웃을 해야하는 경험을 한 적이 있습니다. 만약 이 훅에 의존을 해서 엑세스토큰만료 에러를 대응하신다면 > '자동 로그인 기간이 만료되었습니다. 다시 로그인해주세요.' 이런식으로 알림을 띄우고 로그아웃 한 다음 로그인 페이지로 이동하는 로직 < 이 꼭 필요해보입니다.

2023-02-07 11:51 UTC, caffesale commented
정석대로 액세스 토큰의 만료기간을 저장하면 1번이 가능하지만 지금 그걸하면 다른 api요청에 부작용이 있을까봐 보류했습니다. 수정 전까지 현재 테스트기간에 활용할 용도이고 그 후에 개량 생각하고 있습니다.

2023-02-08 03:38 UTC, YesunPark commented
1. '정석대로 액세스 토큰의 만료기간을 저장하면 1번이 가능하지만' 의 '정석대로'라는게 어떤 정석을 말씀하시는지 잘 모르겠습니다.

2. '정석대로 액세스 토큰의 만료기간을 저장하면 1번이 가능하지만' 의 '1번'이라는게 제 최근 답글 중 2 -1)을 말씀하시는 건가요?

3. 테스트기간에 활용하고 그 후에는 어떻게 개량하실 건가요?? 지금 상태가 제 최근 답변 중 2번이 충족이 안되는 상태라면 만약 한번 로그인 후 사이트를 나갔다가 5시간 후에 다시 들어올 때(로그인이 되어있는 상태, 하지만 액세스 토큰은 만료된 상태) 토큰이 필요한 요청을 하면 동규님 코드에서는 계속 오류가 날거고(사용자는 오류나는지도 모름. 로그인 다시 하라는 안내도 안해주고, alert도 안뜨고, 그냥 작동 안 됨) 그 부분에 대한 대처가 필요해보여요ㅠㅠ 테스트기간에 활용하신다는 것도 이 부분이 안되면 활용이 불가능해보입니다

2023-02-08 12:25 UTC, caffesale commented
구체적인 방법은 다음과 같습니다

1. JSON.stringify({ accessToken: aslkdfjklsdf, expired: date })로 저장 후 JSON.parse()해서 expired값과 new Date()를 비교한 뒤에 new Date값이 더 크면 refresh요청을 보낸다. 혹은 만료되기 x * 1000밀리초 전에 요청하거나 localstorage에 액세스 토큰을 받아올 때 expired를 생성해 key=value 페어로 보관한 뒤 참조한다. 

2. 웹 어플이 불려올 때 훅도 자동으로 동작하니 현재 커스텀 훅 내에 if(accessToken) ... 구문을 추가한다. 

헌데 시간이 모자란 상황이니 일단 클로즈 하겠습니다

2023-02-08 14:23 UTC, YesunPark commented
넵 알겠습니다

2023-02-09 11:43 UTC, closed without merging