Feat: 마이페이지 한줄리뷰, 블로그 리뷰 추가
myalley-project/myalley-fe pull request #263
Opened 2023-02-06 15:27 UTC by caffesale

2023-02-06 17:50 UTC, YesunPark requested changes

2023-02-06 17:50 UTC, YesunPark commented on src/apis/member.tsx
> +    id: string;
id 타입은 number인 것 같습니다

2023-02-06 17:50 UTC, YesunPark commented on src/components/mypage/WrittenBlogReview.tsx
> +  /* flex-flow: row wrap; */
주석 필요없는 거면 삭제부탁드립니다!

2023-02-06 17:50 UTC, YesunPark commented on src/components/onelineReview/presentation/OnelineCard.tsx
>          )}
풀받아서 테스트해봤는데 프로필 이미지가 있든 없든 다 안나옵니다.
     <img
          src={memberInfo?.memberImage ? memberInfo.memberImage : ProfileImg}
          alt="사람 이미지"
        />

이렇게 바꾸셔야해요 userImage에서 memberImage로 변경됐는데 반영을 못하신 것 같습니다

2023-02-06 17:50 UTC, YesunPark commented on src/components/onelineReview/presentation/OnelineCard.tsx
>          )}
그리고 profileImg로 수정해주세요~

2023-02-07 12:54 UTC, caffesale commented
수정사항은 반영했지만 브랜치히스토리가 꼬여서 닫고 다른 브랜치에 반영해 올리겠습니다

2023-02-07 12:56 UTC, closed without merging