Feat: 블로그 디테일 버튼 작업 완료
myalley-project/myalley-fe pull request #274
Opened 2023-02-07 14:10 UTC by caffesale

- 좋아요, 북마크 api 추가했습니다
- 현재 북마크 api에 문제가 있습니다. 응답은 on, off가 정상적으로 전환되는데 블로그 상세 페이지 조회 api에는 북마크 수와 여부에 변화가 없습니다. 일단 백엔드에 언급한 상태입니다. 
- usemutation을 통해 요청 성공 시 조회 api의 쿼리 키를 무효화하고 다시 받아오고 있기 때문에 따로 응답 값에 따라 처리할 필요가 없습니다.

2023-02-07 15:47 UTC, YesunPark requested changes
코멘트 확인부탁드립니다~

2023-02-07 15:47 UTC, YesunPark commented on src/apis/bookMarkApis.tsx
> +import apiInstance from "../utils/apiInstance";
북마크는 블로그만 북마크가 있는게 아니기 때믄에 파일명 수정부탁드립니다!!! 블로그리뷰 관련 api 모아두신 파일 있던데 아예 그 파일에 추가로 작성하셔도 괜찮지 않을까싶네요

2023-02-08 12:45 UTC, caffesale commented on src/apis/bookMarkApis.tsx
> +import apiInstance from "../utils/apiInstance";
파일명 수정했고 기능도 수정해서 올렸습니다. 확인 부탁드립니다.

2023-02-08 13:13 UTC, YesunPark approved these changes

2023-02-09 13:45 UTC, merged