Fix: 전시회 게시물에서 리뷰가 없는 경우 Nolist 컴포넌트 표시
myalley-project/myalley-fe pull request #359
Opened 2023-02-10 16:06 UTC by caffesale

2023-02-10 16:37 UTC, gandy818 approved these changes
확인했습니다.

2023-02-10 19:55 UTC, YesunPark requested changes

2023-02-10 19:55 UTC, YesunPark commented on src/pages/BlogReviewDetail.tsx
> +      <Divider />
이 부분 dev와 달라서 확인부탁드려요! dev대로 적용해주셔야 합니다!
(전시 상세페이지 상단 배경있는 전시회 카드 부분 변경하며 변경됐습니다)
컴포넌트명도 BlogReview로 변경되었어요
컨플릭트 꼭 확인 후 머지해주세요~

2023-02-11 00:21 UTC, caffesale commented on src/pages/BlogReviewDetail.tsx
> +      <Divider />
로컬에서 충돌 해결 후 푸시했습니다

2023-02-11 00:32 UTC, YesunPark approved these changes

2023-02-11 00:32 UTC, YesunPark commented
병합커밋이 컨벤션에 안맞는게 있으셔서 스쿼시머지로 부탁드려요~

2023-02-11 04:34 UTC, caffesale commented
넵

2023-02-11 04:35 UTC, merged