Feat: 블로그리뷰 및 캘린더 컴포넌트 수정
myalley-project/myalley-fe pull request #394
Opened 2023-02-14 12:59 UTC by caffesale

1. 블로그리뷰 상세 주차공간 => 교통수단 표기로 변경
2. 블로그리뷰 삭제시 확인창 띄우기 
3. 삭제된 뒤 작성글 목록 리프레시 : 2번 처리하면서 필요가 없어졌습니다
4. 리뷰목록 별점순, 최신순, 네이게이터에 포인터 추가
5. 검색창 입력시 알림 추가
6. 전시회 선택 컴포넌트 호버효과 추가
7. 캘린더 컴포넌트 오동작 수정
8. 비로그인 상태시 블로그리뷰 작성페이지로 이동 막기
9. 블로그리뷰 라우팅 추가

2023-02-14 13:01 UTC, caffesale commented on src/components/Calendar.tsx
> +  const initialDate = !selectedDate ? new Date() : selectedDate;
프롭스로 받는 selectedDate에 디폴트 값으로 null을 추가했습니다.
이렇게 하면 selectedDate를 내려주지 않을 때 새로운 date를 생성하여 기본값으로 사용하고, selectedDate가 존재하면 그 값을 초기값으로 설정합니다

2023-02-14 13:02 UTC, caffesale commented on src/components/Calendar.tsx
> -
제출용 state는 상위 컴포넌트에서 handleSelectedDate로 관리하고 렌더링에 필요한 state는 해당 컴포넌트에서 자동으로 리렌더링되기 때문에 useEffect를 없앴습니다.

2023-02-14 18:27 UTC, YesunPark commented on src/components/Calendar.tsx
> +  const initialDate = !selectedDate ? new Date() : selectedDate;
넵 좋습니다!

2023-02-14 18:34 UTC, YesunPark commented on src/components/Calendar.tsx
> -
렌더링에 필요한 state가 자동으로 리렌더링이 되지 않아서 useEffect를 추가했던 건데 혹시 확인해보셨나요??

ex) 메이트글 작성 시 2월20일로 날짜 선택 후 작성 완료했는데, 수정버튼 클릭해서 들어가보면 2월 20일이 아닌 현재날짜가 뜸.
넘겨주는 selectedDate가 상위컴포넌트에서 상태가 업데이트 될 때 자식컴포넌트인 Calendar에는 한번 값이 넘겨지고 그 다음 상태값이 업데이트 될 때 리렌더링이 자동으로 되지 않아서 발생하는 것 같아서 useEffect넣었던 거에요

만약 이 문제가 없다면 useEffect 삭제해주셔도 될 것 같아요! 확인부탁드려요

+) 그리고 문제없어서 삭제하실거면
clickArrowLeft 함수에 setShowedMonth(prevDate);
clickArrowRight 함수에 setShowedMonth(nextDate);
이 로직 추가해주셔야 달력의 왼쪽 오른쪽 버튼 화살표 눌렀을 때 달이 바뀔거에요~!

결론 - 2가지 부분 확인해주셔서 에러 없으면 제 pr은 닫아도 될 것 같네요!
1. 수정버튼 클릭해서 들어갔을 때 현재 날짜가 아닌 등록했던 날짜가 잘 뜨는지 (메이트글 작성,수정 페이지에서도 꼭 확인해주세요)
2. useEffect 삭제함으로서 달력 좌/우 화살표를 눌렀을 때 달이 안바뀌는 에러가 없는지

2023-02-14 18:35 UTC, YesunPark requested changes
코멘트 달았습니다
2가지 확인이 필요할 것 같은데, 이 부분이 다 확인되면 머지하시고
제가 수정해서 올린 pr은 닫아도 될 것 같네요 확인부탁드려요!

2023-02-15 02:13 UTC, gandy818 approved these changes

2023-02-15 02:13 UTC, gandy818 commented on src/components/onelineReview/container/OneLineReadContainer.tsx
> +        )}
동규님 여기 밑에 페이지네이션이요!
페이지네이션 컴포넌트 자체에 갯수가 0이면 안보이도록 설정이 되어있어서 굳이
삼항 연산자를 쓸 필요가 없어보입니다. 나중에 여유되실때 정리해주시면 좋을것같아용

2023-02-15 02:13 UTC, gandy818 commented on src/components/blogreview/container/BlogReviewTop.tsx
> +      deleteReviewMutation.mutate();
삭제하시겠습니까? 부분 저희 컨벤션 맞추기로 해서 (프론트 채널에서 확인 가능하십니다)
simpleModal로 바꿔주시면 좋을 것 같아요! 급한 작업은 아니니 우선 기능 오류부터 수정하시구
여되실때 수정해주시면 좋을 것 같습니다 ㅎㅎ

2023-02-15 12:56 UTC, caffesale commented on src/components/Calendar.tsx
> -
2번은 괜찮은데 1번에 문제가 생기네요... 해결해보려하니 렌더링에 문제생겨서 캘린더 컴포넌트는 예선님 버전으로 교체하겠습니다.

2023-02-15 13:09 UTC, caffesale commented on src/components/Calendar.tsx
> -
예선님이 커밋하신 버전으로 교체한 뒤 dev와 합쳐서 다시 푸시 했습니다.

2023-02-15 13:10 UTC, caffesale commented on src/components/onelineReview/container/OneLineReadContainer.tsx
> +        )}
이 부분 수정해서 다시 푸시 했습니다.

2023-02-15 13:11 UTC, caffesale commented on src/components/blogreview/container/BlogReviewTop.tsx
> +      deleteReviewMutation.mutate();
넵 이건 다음번 pr에 반영하겠습니다

2023-02-15 13:36 UTC, YesunPark approved these changes

2023-02-15 13:36 UTC, YesunPark commented
확인했습니다 :)

2023-02-15 13:37 UTC, merged