Setting: 자간 설정 추가, 파일명 수정
myalley-project/myalley-fe pull request #54
Opened 2023-01-12 12:03 UTC by gandy818

- 모든 글자에 letter-spacing: -0.5px; 속성이 있는 것을 확인했습니다.
하드코딩하는 것보다 전역으로 관리하는 게 편할 것 같아서 Global style에 추가합니다.

- 파일명은 파스칼케이스로 하기로 했었는데 해당 파일들이 소문자로 시작하여 파일명을 수정했습니다.

2023-01-12 12:08 UTC, YesunPark requested changes
컴포넌트 파일만 파스칼이고 나머지 파일들은 카멜인걸로 알고있는데 혹시 제가 잘못알고 있는걸까요?
apiInstance나 타입관련 파일들도 컴포넌트 파일이 아니라서 카멜로 하고 머지했었거든요!
한번 확인 부탁드립니다

2023-01-12 12:15 UTC, gandy818 commented
헛 그러고보니 저희가 음성채널에서 회의할때 이미지 파일 / 컴포넌트 파일만 두고 얘기를 해서 
정확하게 정해진 부분이 아니였군요..! 
저는 당연히 svg 같은 이미지 파일을 제외하고 나머지 tsx 파일은 파스칼케이스라고 생각하고 있었습니다.
이부분은 저희가 맞추면 될 것 같은데 어떻게 하는것이 좋을까요??

2023-01-12 12:16 UTC, YesunPark commented
> 헛 그러고보니 저희가 음성채널에서 회의할때 이미지 파일 / 컴포넌트 파일만 두고 얘기를 해서 정확하게 정해진 부분이 아니였군요..! 저는 당연히 svg 같은 이미지 파일을 제외하고 나머지 tsx 파일은 파스칼케이스라고 생각하고 있었습니다. 이부분은 저희가 맞추면 될 것 같은데 어떻게 하는것이 좋을까요??

저는 컴포넌트 파일만 파스칼, 나머지는 카멜로 하면 좋을 것 겉습니다!

2023-01-13 02:45 UTC, caffesale commented
그게 구별하기 쉬울 것 같네요. 저도 찬성합니다

2023-01-13 03:17 UTC, YesunPark approved these changes

2023-01-13 04:49 UTC, gandy818 commented
넵 수정 후 머지하겠습니다! globalStyles 파일의 경우 기존에 케밥케이스로  명명되어있어서 푸시하실때 한번씩 체크 부탁드릴게요

2023-01-13 04:51 UTC, merged