Design: 메인페이지 카드 컴포넌트 추가
myalley-project/myalley-fe pull request #59
Opened 2023-01-14 06:54 UTC by caffesale

- 전시회, 전시 리뷰, 메이트 카드 ui 추가
- navigate, media query 미구현
- 아이콘 차후 대체 예정

2023-01-14 15:56 UTC, YesunPark requested changes
고생하셨습니다! feature/articles 브랜치의 몇가지 수정 후 머지 부탁드려요
1. 현재 dev의 asset에는 없는 menu 등의 icon이 존재함 (이름바뀌었는데 병합을 안해주셔서 아직 존재하는 것 같습니다)
2. dev-component-exhibition과 컴포넌트 이름이 다름.

dev브랜치와 내용 다른 부분이 있어서 dev에 머지하기 전에 dev랑 병합 한번부탁드려요~

2023-01-14 15:56 UTC, YesunPark commented on src/components/MainArticle.tsx
> +  text-align: center;
[저희 css 순서 컨벤션](https://www.notion.so/FrontEnd-Convention-b8f0fc07365a43fe804c2acf47697c71#b4c2be4acf4b4e308749bee4359dfa90)에 맞게 
display, list-style, padding, border, text-align 이런 순서로 수정해주시면 더 좋을 것 같습니다!

2023-01-14 15:56 UTC, YesunPark commented on src/components/MainArticle.tsx
> +    margin-bottom: 1rem;
이런 곳도요! margin-> font관련

2023-01-17 11:32 UTC, caffesale commented
오 순서를 깜빡 하고 있었는데 수정 후 다시 요청하도록 하겠습니다.

2023-01-18 01:49 UTC, caffesale commented
@YesunPark  메인 아티클 순서 수정했습니다. 어제 작업한 다른 컴포넌트들도 순서를 신경 못 썼는데 작성해가면서 수정하겠습니다.

2023-01-18 05:55 UTC, caffesale commented on src/components/MainArticle.tsx
> +    margin-bottom: 1rem;
메인 아티클 css 순서 수정했습니다. 어제 작업한 다른 컴포넌트들도 순서를 신경 못 썼는데 작성해가면서 수정하겠습니다.

2023-01-18 06:20 UTC, YesunPark commented
승인했습니다!

2023-01-18 06:49 UTC, merged