Feat: 메인페이지 슬라이더 추가
myalley-project/myalley-fe pull request #60
Opened 2023-01-14 07:34 UTC by caffesale

- !! swiper 라이브러리를 추가했기 때문에 pull 이후에 yarn i 해주셔야 합니다. 
- 메인페이지 슬라이더 ui 추가했습니다.
- 백그라운드 이미지는 정해지는 대로 반영하겠습니다.

2023-01-14 15:58 UTC, YesunPark requested changes
내용전부 확인했습니다, 다만 이 브랜치도 dev와 내용 다른 부분이 좀 있어서 dev 병합 후 머지부탁드릴게요~

2023-01-18 03:44 UTC, caffesale commented
- dev와 병합했습니다
- 메인 페이지 이미지 적용 마쳤습니다
- 블러 효과 추가했습니다

2023-01-18 06:21 UTC, YesunPark approved these changes

2023-01-18 06:21 UTC, YesunPark commented
승인했습니다~

2023-01-19 05:01 UTC, merged