Feat: 전시글 작성 페이지 작업, selectbox 컴포넌트 완성
myalley-project/myalley-fe pull request #88
Opened 2023-01-19 18:52 UTC by gandy818

‼ react-datepicker 라이브러리가 추가되었습니다. 각자의 로컬에서 라이브러리를 설치해주거나 yarn 명령어로 다시 install 해주세요 ‼
- 관리자용 전시글 작성 페이지 UI 작업을 1차적으로 끝냈습니다. 관련 로직은 추후 추가할 예정입니다.
- selectbox 컴포넌트를 완성했습니다. 기존의 동규님이 만드신 selector 파일을 참고하여 만들었고 동규님 파일을 지우면 곳곳에서 에러가 날까봐 우선 삭제하진 않았습니다. 안전하게 아무곳에서도 사용이 안될 때 삭제하겠습니다.
- selectbox는 4가지의 props를 받습니다. 아무것도 선택되지 않았을 때 보여지는 값인 placeholder, 선택된 값을 가져오는 selectedData, 옵션의 목록을 불러오는 options, 셀렉트박스의 넓이인 width가 있습니다. 추가적으로 이해가 안되는 부분이 있다면 코멘트 달아주세요
- 전반적으로 디테일한 부분을 많이 신경 못썼습니다. 우선 큰 ui나 로직부터 잡고 세밀한 부분은 리팩토링 과정에서 잡고자 합니다.
- AdminWriteExhibition 파일에서 어디까지가 랜더링에 관련한 함수이고 어디까지가 관련이 없는 함수인지 경계가 애매해서 분리를 못시켰습니다. 이 부분 관련해서 조언을 해주시면 감사하겠습니다.

2023-01-20 06:42 UTC, YesunPark requested changes
확인했습니다~!
아이콘에 radioOff, radioOn은 삭제하고, dev에 추가된 check로 수정한 뒤 머지 부탁드립니다!
changes requested는 아이콘들 때문에 걸었고, 밑에는 참고만 해주세요:)

그리고 몇가지 의견이 있어서, 참고부탁드려요!
1.  AdminWriteExhibition은 관리자가 전시글 작성하는 페이지 같은데, 혹시 ExhibitionWrite라고 이름 변경하는건 어떠신가요? Exhibition, ExhibitionList 이런식으로 네이밍이 되어있어서 Exhibition으로 시작하도록 통일이되면 폴더 내에서 파일이 순서대로 나열되니까 나중에 보기 편할 것 같아요!
개인적으로 Admin도 안붙여도 되는 부분같은데(왜냐면 회원용 전시글 작성, 관리자용 전시글 작성이 나뉘어져 있는게 아니라 전시글 작성페이지는 어차피 관리자만 접근 가능하니까요!) 붙이는게 편하시면 ExhibitionWriteAdmin이런식으로 변경해주셔도 좋을 것 같습니다 :)

2. AdminWriteExhibiton 페이지
get이라는 동사는 보통 서버에서 데이터를 가져오거나 할 때 사용한다고 해요, 지금 보면 input이나 textArea처럼 사용자의 입력에 따라 발동하는 함수는 저희 handle로 쓰기로 했으니(프론트 컨벤션 페이지 참고해주세요 handleTitleInput, handleWebLinkInput 이런식으로 함수명 변경해주시면 더 좋을 것 같아요~

3. 지금 똑같은 역할을 하는 함수가 여러개 보이는데(getTitle, getAuthor, getWebLink, getContent), 이거 하나의 handleInputAndTextArea 이라는 함수로 통일시킬 수 있을 것 같아요!
제가 작성했던 코드링크 드릴게요 https://github.com/myalley-project/myalley-fe/blob/0c51111e03a6c3f53fc83cf9aa90224db2ac72c5/src/pages/SignUp.tsx#L40-L47
이런식으로 input, TextArea에 입력되는 값을 하나의 함수로 통제할 수 있으실 것 같아용
React.ChangeEvent<HTMLInputElement> | React.ChangeEvent<HTMLTextAreaElement>
이렇게 e의 타입만 두개로 주면 되지 않을까 싶습니당

2023-01-20 14:16 UTC, gandy818 commented
@YesunPark  
1. 아이콘 삭제, 변경된 아이콘 반영해서 수정 완료하였습니다.
2. 파일명, 함수명 수정완료했습니다. 
3. 와 너무 좋은 방법이 있었네요!! 피드백 감사합니다. 바로 수정했어요 ㅎㅎ

2023-01-20 16:16 UTC, YesunPark approved these changes
고생하셨습니다ㅠㅠ 확인완료입니다!
몇가지 더 발견하긴 했는데 참고해주세요!

2023-01-20 16:16 UTC, YesunPark commented on src/pages/ExhibitionWrite.tsx
> +const AdminWriteExhibition = () => {
컴포넌트 명이 파일명과 통일이 안된것 같습니다!

2023-01-20 16:16 UTC, YesunPark commented on src/pages/ExhibitionWrite.tsx
> +  };
함수명 handlePriceFree로 변경 부탁드려요!

2023-01-21 06:31 UTC, caffesale commented
수고하셨습니다 b

2023-01-21 07:49 UTC, gandy818 commented
모든 수정사항 완료했습니다~

2023-01-21 07:50 UTC, merged